# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VEUJZym6TqmoWxT_foHOd-kvzIIXcxK
"""

Resumen

"""La inteligencia artificial avanzada es un área de la informática que busca crear sistemas capaces de aprender de los datos, reconocer patrones, hacer predicciones y tomar decisiones. Dentro de la IA encontramos el aprendizaje automático o Machine Learning, donde los modelos aprenden a partir de datos para resolver diferentes problemas.

Uno de los conceptos importantes es el truco de Kernel, utilizado principalmente en algoritmos como las máquinas de soporte vectorial o SVM. Su función es permitir trabajar con problemas que no pueden separarse de forma lineal, utilizando funciones llamadas kernels para representar los datos de una manera que facilite su clasificación.

En los modelos de clasificación es muy importante evaluar qué tan bien funcionan. Para ello se utiliza la matriz de confusión, que contiene cuatro resultados: verdaderos positivos, verdaderos negativos, falsos positivos y falsos negativos. A partir de estos valores se pueden calcular diferentes métricas. El Recall indica qué cantidad de los positivos reales consiguió detectar el modelo. La Precision indica cuántos de los casos que el modelo clasificó como positivos realmente eran positivos. El F1-score combina Precision y Recall y permite medir el equilibrio entre ambas.

Otra herramienta de evaluación es la curva ROC, que representa la relación entre la tasa de verdaderos positivos y la tasa de falsos positivos cuando se modifica el umbral de clasificación. El área bajo esta curva, conocida como ROC-AUC, sirve para medir la capacidad del modelo de distinguir entre diferentes clases.

Scikit-learn es una de las principales bibliotecas de Python para Machine Learning. Permite preparar los datos, entrenar modelos, hacer predicciones, evaluar resultados y optimizar los parámetros de los modelos. Entre los modelos supervisados se encuentran la regresión logística, los árboles de decisión, Random Forest, SVM, KNN y diferentes métodos de boosting.

El aprendizaje supervisado consiste en entrenar un modelo utilizando datos de entrada y una respuesta conocida o etiqueta. Cuando el modelo predice categorías hablamos de clasificación, mientras que cuando predice valores numéricos hablamos de regresión.

También existen técnicas de combinación de modelos, como Bagging y Boosting. Bagging consiste en entrenar varios modelos y combinar sus resultados, buscando principalmente reducir la variabilidad del modelo. Un ejemplo conocido es Random Forest. Boosting, en cambio, construye modelos de manera secuencial, haciendo que cada nuevo modelo intente corregir los errores de los anteriores. Algunos ejemplos son AdaBoost, Gradient Boosting, XGBoost y otros.

Por último, RandomizedSearchCV es una herramienta de Scikit-learn utilizada para buscar buenos hiperparámetros. En lugar de probar todas las combinaciones posibles, selecciona aleatoriamente un número determinado de combinaciones y las evalúa mediante validación cruzada. Esto permite encontrar configuraciones adecuadas para un modelo de forma más eficiente.

En resumen, para desarrollar un buen modelo de Machine Learning no basta con entrenarlo: también hay que seleccionar el algoritmo adecuado, ajustar sus hiperparámetros y utilizar métricas como Precision, Recall, F1-score, ROC-AUC y la matriz de confusión para comprobar su rendimiento.

"""